### PR TITLE
Added class version to the file name

### PR DESCRIPTION
**Pull request by Mmiglio**
Renamed test file to include class version, as requested in this comment https://github.com/cms-data/DataFormats-L1ScoutingRawData/pull/1#discussion_r1459284313.

### CODE REVIEW

**Comment by smorovic** [comment]
please test

**Comment by smorovic** [comment]
+daq

**Comment by smuzaffar** [comment]
+externals

@Mmiglio , is there any cmssw PR which uses this new (renamed) file?

**Comment by Mmiglio** [comment]
Hi @smuzaffar, shall I proceed with the PR using this files or wait for this PR to be merged before opening one in CMSSW?

**Comment by smuzaffar** [comment]
@Mmiglio , please proceed with the cmssw PR which uses this file. CMSSW PR can be tested together with this PR

**Comment by rappoccio** [comment]
+1

**Pull request merged**
